language: java
jdk: oraclejdk8

#install dependencies
#mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
- mvn clean verify
- mvn clean install